### Read data 
GET http://localhost:4004/odata/v4/StudentDetails/Students

### Read single record based on student id
GET http://localhost:4004/odata/v4/StudentDetails/Students(101)

### Read single student record with few fields of school 
GET http://localhost:4004/odata/v4/StudentDetails/Students?$expand=school($select=school_id,Curriculum)


### Read single record including all fields of school 
GET http://localhost:4004/odata/v4/StudentDetails/Students?$expand=school


### Create Student Record
POST http://localhost:4004/odata/v4/StudentDetails/Students
Content-Type: application/json

{     "student_id": 201,
      "firstName": "first name",
      "lastName": "last name",
      "dateOfBirth": "2000-04-14",
      "dateOfJoining": "2014-04-14",
      "email": "tes2t@gmail.com",
      "phoneNumber": "9234567890",
      "school_school_id": 199 }


### Read School data 
GET http://localhost:4004/odata/v4/StudentDetails/Schools 

### Create school Record
POST http://localhost:4004/odata/v4/StudentDetails/Schools
Content-Type: application/json

    {     
      "school_id": 199,
      "SchoolName": "Test School 2",
      "Principal": "test Principal 2",
      "SchoolStrength": 400,
      "Curriculum": "ICSE",
      "rating": "B"
    }